# Generated by Django 5.1.7 on 2025-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)'),
        ),
    ]
