# Generated by Django 5.1.7 on 2025-10-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_productprice_price'),
        ('shop', '0005_alter_product_pressure_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='سایز لوله')),
                ('pressure', models.PositiveIntegerField(verbose_name='فشار (بار)')),
                ('pe_type', models.CharField(choices=[('PE80', 'PE80'), ('PE100', 'PE100')], max_length=5, verbose_name='نوع PE')),
                ('weight', models.FloatField(default=0.0, verbose_name='وزن لوله (کیلوگرم)')),
                ('price_per_kg', models.IntegerField(default=0, verbose_name='قیمت هر کیلوگرم (تومان)')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='shop.product', verbose_name='محصول مرتبط')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
