# Generated by Django 5.1.7 on 2025-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='سایز لوله')),
                ('pressure', models.PositiveIntegerField(verbose_name='فشار (بار)')),
                ('pe_type', models.CharField(max_length=20, verbose_name='نوع PE')),
                ('price_per_kg', models.FloatField(verbose_name='قیمت هر کیلوگرم (تومان)')),
            ],
        ),
    ]
