# Generated by Django 5.1.7 on 2025-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeprice',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='وزن لوله (کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='pipeprice',
            name='pe_type',
            field=models.CharField(choices=[('PE80', 'PE80'), ('PE100', 'PE100')], max_length=5, verbose_name='نوع PE'),
        ),
    ]
