# Generated by Django 5.1.7 on 2025-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pipeprice_weight_alter_pipeprice_pe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.FloatField(verbose_name='قیمت هر کیلوگرم (تومان)')),
            ],
        ),
        migrations.RemoveField(
            model_name='pipeprice',
            name='price_per_kg',
        ),
    ]
