# Generated by Django 5.1.7 on 2025-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricesetting_remove_pipeprice_price_per_kg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceSetting',
        ),
        migrations.AddField(
            model_name='pipeprice',
            name='price_per_kg',
            field=models.FloatField(default=0.0, verbose_name='قیمت هر کیلوگرم (تومان)'),
        ),
    ]
