# Generated by Django 5.1.7 on 2025-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_delete_pricesetting_pipeprice_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeprice',
            name='price_per_kg',
            field=models.IntegerField(default=0, verbose_name='قیمت هر کیلوگرم (تومان)'),
        ),
    ]
