# Generated by Django 5.1.7 on 2025-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pipeprice_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeprice',
            name='pressure',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='بار'),
        ),
    ]
