# Generated by Django 5.1.7 on 2025-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_pipeprice_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeprice',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='سایز لوله/اینچ'),
        ),
    ]
