# Generated by Django 5.1.7 on 2025-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_pipeprice_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeprice',
            name='pressure',
            field=models.FloatField(default=6.0, verbose_name='بار'),
        ),
    ]
