# Generated by Django 5.1.7 on 2025-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_pipeprice_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeprice',
            name='size',
            field=models.IntegerField(verbose_name='سایز لوله/اینچ'),
        ),
    ]
