# Generated by Django 5.1.7 on 2025-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, choices=[('تبریز', 'تبریز'), ('مراغه', 'مراغه'), ('مرند', 'مرند'), ('اهر', 'اهر'), ('بناب', 'بناب'), ('میانه', 'میانه'), ('شبستر', 'شبستر'), ('هشترود', 'هشترود'), ('سراب', 'سراب'), ('آذرشهر', 'آذرشهر'), ('اسکو', 'اسکو'), ('بستان\u200cآباد', 'بستان\u200cآباد')], max_length=30, null=True, verbose_name='شهر'),
        ),
    ]
