# Generated by Django 5.1.7 on 2025-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام خبر')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='تصویر خبر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
