# Generated by Django 5.1.7 on 2025-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
