# Generated by Django 5.1.7 on 2025-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('load_capacity', models.CharField(max_length=100, verbose_name='میزان بار')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
            ],
        ),
    ]
