# Generated by Django 5.1.7 on 2025-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_load_capacity_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قطر (میلی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pressure',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='فشار (بار)'),
        ),
    ]
