# Generated by Django 5.1.7 on 2025-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_diameter_product_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.AddField(
            model_name='product',
            name='pe_type',
            field=models.CharField(choices=[('PE80', 'PE80'), ('PE100', 'PE100')], default='PE100', max_length=10, verbose_name='نوع پلی\u200cاتیلن'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('1_inch', '1 اینچ'), ('2_inch', '2 اینچ'), ('50_mm', '50 میلی\u200cمتر'), ('100_mm', '100 میلی\u200cمتر')], default='63', max_length=20, verbose_name='سایز لوله/اینچ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pressure',
            field=models.PositiveIntegerField(null=True, verbose_name='بار'),
        ),
    ]
