# Generated by Django 5.1.7 on 2025-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_diameter_product_pe_type_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pressure',
            field=models.PositiveIntegerField(default=6, verbose_name='بار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=50, verbose_name='سایز لوله/اینچ'),
        ),
    ]
