# Generated by Django 5.1.7 on 2025-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_pressure_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pressure',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='بار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='سایز لوله/اینچ'),
        ),
    ]
