# Generated by Django 5.1.7 on 2025-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_pressure_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(verbose_name='سایز لوله/اینچ'),
        ),
    ]
