# Generated by Django 5.1.7 on 2025-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='national_id',
            field=models.CharField(default='', max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ'),
        ),
    ]
