# Generated by Django 5.1.7 on 2025-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_full_name_order_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
